name = "bluenamber"
main = "src/index.js"
compatibility_date = "2026-10-08"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "bluenamber-db"
database_id = "ce9256bb-8ec0-4b7c-ac3a-259091d154e5"

[vars]
ENABLE_PURCHASES = "false"
PROVIDER = "callinoo"
